### ISSUE TITLE
Any words on OpenRethinkdb?

### ISSUE THREAD

**Issue by v3ss0n** [coffeemug/defstartup#1]
Thank you very much for the writeup @coffeemug . Would be nice if you can disclose more. 

### While you were gone
- @Atnnn and @srh resumed  development and then a few from community continued working on OpenRethinkdb   . 
- Many of us are are willing to support development , and waiting for the time we can actually start donating. 
- Since development resumed and commits flowing back, many new users joined into slack chat room . We had to answer questions almost every hours.

As a founder of six years old tech startup and we built our tech stack around RethinkDB and Realtime since you introduced rethinkdb on one of my Quora question , i  am very grateful for Rethinkdb and i had learnt a lot how you guys work over the github, and replicated alot of it. Thank you very much for your wisdom and knowledge. But i still believe , it was too soon.

**Comment by v3ss0n** [comment]
### A few thing that could have done (i know its too late) : 
- if you wanted to compete with firebase , market it in China, coz they blocked GCM/FCM and it is huge  tech market.
- should have focused on rethinkdb alone (not the cloud or horizon) and odoo style "RethinkDB Contrators" would be great.

**Comment by coffeemug** [comment]
I decided not to participate in the OpenRethinkDB project, and I haven't kept up to date on its status. For anyone reading, if you'd like to participate, the best way is to join `#open-rethinkdb` on Slack.

**Comment by v3ss0n** [comment]
Thank you very much , just want to know your opinions about feasibility of OpenRethinkDB , but i don't think you want to say . would be nice if you can point on your website  a few links :

chatroom : https://rethinkdb.slack.com/messages/open-rethinkdb/
help : https://rethinkdb.slack.com/messages/general
current info and latest status : https://docs.google.com/document/d/1f8qODp7voKIqwioQ3si69q3-ruc7h3ncfH0KoHYv_4k

I am sorry i won't nag you anymore.
