### ISSUE TITLE
Could you elaborate on how The Economist make you better as a founder?

### ISSUE THREAD

**Issue by yogurt-island-331** [coffeemug/defstartup#3]
In the essay `why-rethinkdb-failed.md`, your last point was that reading The Economist will make you better faster, could you elaborate on why and given an example?  That would be super helpful.  Thanks!

**Comment by Akamaozu** [comment]
+1 this. Was about to ask this question

**Comment by screenshotjy** [comment]
Read it to find out.

**Comment by coffeemug** [comment]
To be successful you need to have an intuition for how market forces affect the world. You probably already know the basics (e.g. supply and demand), but there is a huge gap between knowing some basic laws and understanding how these laws interact to apply to your specific problem domain (knowing the rules of chess alone does not make you a grandmaster). 

The Economist is built around the culture of viewing current events through the lens of economics. Reading it is the best way I know of to develop this intuition quickly (other than getting a degree in economics, which is obviously a bit heavy-handed).

**Comment by yogurt-island-331** [comment]
@coffeemug thanks! That makes a lot of sense 👍

**Comment by sah2ed** [comment]
@coffeemug agree with your *The Economist* recommendation.

You could also point people to [Finimize](https://www.finimize.com/)'s daily newsletter. They do a decent job of teaching economics by explaining current events using every day language.

I should add that I have absolutely no relationship to them whatsoever; I'm merely a subscriber to the global edition of their newsletter.
